# Generated by Django 5.1 on 2024-08-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='titel',
            new_name='title',
        ),
    ]
