# Generated by Django 5.1 on 2024-08-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_titel_category_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='titel',
            new_name='title',
        ),
    ]
