# Generated by Django 5.1 on 2024-08-09 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_titel_product_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='titel',
            new_name='title',
        ),
    ]
